// Generated by scripts/generate-binary-patch-registry.py.
// Do not edit by hand.

enum GeneratedBinaryPatchRuleRegistry {
    static let modules: [BinaryPatchRuleModule.Type] = [
        BinaryAdsPatchModule.self,
        BinaryCorePatchModule.self,
        BinaryInlinePatchModule.self,
        BinaryMonetizationPatchModule.self,
        BinaryRuntimePatchModule.self,
        BinaryStoriesPatchModule.self,
        BinaryVisualPatchModule.self,
    ]
}
