#!/usr/bin/env python3
"""Compile scripts/tl_schema.json into a compact C data fragment for the in-dylib TL decoder.

Emits (to stdout) the body that replaces the __PATCHGRAM_TL_SCHEMA_PLACEHOLDER__ region in
engine.c.template: a string pool + sorted ctor table + param table, with every param type
PRE-COMPILED into opcodes so the C runtime never string-parses a TL type.

Opcodes (must match the enum in engine.c.template):
  0 INT  1 LONG  2 DOUBLE  3 STRING  4 BYTES  5 INT128  6 INT256
  7 FLAGS(#)  8 TRUE  9 BOXED (read ctor id + recurse; covers Bool/Object/!X/Capitalized)
  10 COMPLEX (un-encodable, e.g. nested Vector → decoder shows <complex> and stops the field)
Param.vec: 0 scalar | 1 Vector<> (boxed, consumes 0x1cb5c415) | 2 vector<> (bare, count only)
Param.flag_idx: 0xFF unconditional, else index (within the ctor) of the flags param it needs.

Usage: scripts/gen_tl_schema_c.py [scripts/tl_schema.json] > /tmp/tl_schema_c.frag
"""
import json, os, re, sys

OP = {"int":0,"#":7,"long":1,"double":2,"string":3,"bytes":4,"int128":5,"int256":6,"true":8}
OP_BOXED, OP_COMPLEX = 9, 10

def base_op(t):
    return OP.get(t.lower(), OP_BOXED)  # Bool/Object/!X/Capitalized/unknown -> boxed

def compile_type(t):
    """-> (vec, op). vec: 0 scalar, 1 Vector<>, 2 vector<>."""
    t = t.strip()
    m = re.match(r'([Vv])ector<(.+)>$', t)
    if m:
        vec = 1 if m.group(1) == "V" else 2
        inner = m.group(2).strip()
        if re.match(r'[Vv]ector<', inner):       # nested vector — not encodable
            return (vec, OP_COMPLEX)
        return (vec, base_op(inner))
    return (0, base_op(t))

def main():
    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "tl_schema.json")
    sch = json.load(open(path, encoding="utf-8"))
    by_id = sch["by_id"]

    # String pool: dedup, each entry NUL-terminated; record byte offset of every string.
    pool_parts = []
    pool_off = {}
    pool_len = 0
    def intern(s):
        nonlocal pool_len
        if s not in pool_off:
            pool_off[s] = pool_len
            pool_parts.append(s)
            pool_len += len(s.encode("utf-8")) + 1
        return pool_off[s]

    ctors = []   # (id, name_off, pstart, pcount)
    params = []  # (name_off, flag_idx, flag_bit, vec, op)
    for cid in sorted(by_id):
        e = by_id[cid]
        name_off = intern(e["name"])
        pstart = len(params)
        flag_index = {}  # flags-field name -> its param index within this ctor
        plist = e["params"]
        for i, (pname, ptype) in enumerate(plist):
            poff = intern(pname)
            if ptype == "#":
                flag_index[pname] = i
                params.append((poff, 0xFF, 0, 0, OP["#"]))
                continue
            cond = re.match(r'(\w+)\.(\d+)\?(.+)$', ptype)
            if cond:
                fvar, bit, sub = cond.group(1), int(cond.group(2)), cond.group(3)
                fidx = flag_index.get(fvar, 0xFE)  # 0xFE = unresolved flags ref (shouldn't happen)
                if sub == "true":
                    params.append((poff, fidx & 0xFF, bit, 0, OP["true"]))
                else:
                    vec, op = compile_type(sub)
                    params.append((poff, fidx & 0xFF, bit, vec, op))
                continue
            vec, op = compile_type(ptype)
            params.append((poff, 0xFF, 0, vec, op))
        ctors.append((int(cid, 16), name_off, pstart, len(plist)))

    out = []
    w = out.append
    w(f"/* Generated by scripts/gen_tl_schema_c.py from tl_schema.json"
      f" (layer {sch.get('layer')}, {len(ctors)} ctors, {len(params)} params). DO NOT EDIT. */")
    # String pool as adjacent NUL-terminated literals (compact; offsets computed above).
    w("static const char g_tl_strpool[] =")
    for s in pool_parts:
        esc = s.replace("\\", "\\\\").replace('"', '\\"')
        w(f'  "{esc}\\0"')
    w(";")
    w(f"static const struct PatchgramTLCtor g_tl_ctors[] = {{")
    for cid, noff, ps, pc in ctors:
        w(f"  {{0x{cid:08x}u,{noff},{ps},{pc}}},")
    w("};")
    w(f"static const unsigned g_tl_ctor_count = {len(ctors)};")
    w("static const struct PatchgramTLParam g_tl_params[] = {")
    for noff, fi, fb, vec, op in params:
        w(f"  {{{noff},{fi},{fb},{vec},{op}}},")
    w("};")
    sys.stdout.write("\n".join(out) + "\n")
    sys.stderr.write(f"ctors={len(ctors)} params={len(params)} strpool={pool_len}B\n")

if __name__ == "__main__":
    main()
