#!/usr/bin/env python3
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "Sources" / "PatchgramCore"
OUTPUT = SOURCE_ROOT / "GeneratedBinaryPatchRuleRegistry.swift"

CLASS_PATTERN = re.compile(
    r"(?m)^\s*(?:(?:public|open|final)\s+)*class\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*BinaryPatchRuleModule\b"
)

modules = []
for path in sorted(SOURCE_ROOT.rglob("*.swift")):
    if path.name in {"GeneratedBinaryPatchRuleRegistry.swift", "BinaryPatchRuleCatalog.swift"}:
        continue
    text = path.read_text(encoding="utf-8")
    for match in CLASS_PATTERN.finditer(text):
        modules.append(match.group(1))

modules = sorted(set(modules))
body = "\n".join(f"        {name}.self," for name in modules)
if body:
    body += "\n"

generated = f"""// Generated by scripts/generate-binary-patch-registry.py.
// Do not edit by hand.

enum GeneratedBinaryPatchRuleRegistry {{
    static let modules: [BinaryPatchRuleModule.Type] = [
{body}    ]
}}
"""

if OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") == generated:
    raise SystemExit(0)

OUTPUT.write_text(generated, encoding="utf-8")
